---
- hosts: jumpbox
  vars:
    instance_name:
      - app1
      - app2
      - frontend
      - db

  tasks:
  - name: Deleting floating IP to "{{ instance_name }}"
    os_floating_ip:
      cloud: ospcloud
      state: absent
      reuse: yes
      server: "{{ item }}"
      network: ext_network
    with_items: "{{ instance_name }}"

  - name: Remove Instance
    os_server:
      cloud: ospcloud
      name: "{{ item }}"
      state: absent
    with_items: "{{ instance_name }}"
