---
- name: install progress
  yum:
    name: postgresql-server
    state: present

- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes

- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

- name: start postgres
  service:
    name: postgresql.service
    state: started
