---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers
#   Unnecessary tasks
#   Unnecessary play(s)

- name: configuration
  hosts: all:!bastions
  gather_facts: false # remove later! speeds up testing
  become: true
  tags: app_install

  roles:
    - common

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  tags: app_install

  roles:
    - haproxy_install

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true
  tags: app_install

  roles:
    - tomcat_deploy
    - apache_deploy

- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true
  tags: app_install

  roles:
    - geerlingguy.postgresql

- name: Deploy AD on Windows machine
  hosts: windows
  gather_facts: true
  become: true
  tags: ad_install

  roles:
    - win_ad_install
